---

# NOTE: the containers DNS-resolution won't work after installing NFTables: https://github.com/nestybox/sysbox/issues/456#issuecomment-1015935133

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: test-ag-nftables-tester
    docker_networks:
      - name: 'test-ag-nftables'
        ipam_config:
          - subnet: '192.168.9.0/24'
            gateway: '192.168.9.254'
    networks:
      - name: 'test-ag-nftables'
        ipv4_address: '192.168.9.1'
    groups: [grp_targets]
    docker_host: 'tcp://molecule-docker.local:2375'
    image: 'ansible0guy/molecule:debian-latest'
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true

  - name: test-ag-nftables-1
    networks:
      - name: 'test-ag-nftables'
        ipv4_address: '192.168.9.2'
    groups: [grp_targets]
    docker_host: 'tcp://molecule-docker.local:2375'
    image: 'ansible0guy/molecule:debian-latest'
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true

provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify  # MUST NOT make changes
    - idempotence
    - check
    - destroy
