---

- name: Prepare
  hosts: all
  tasks:
    - name: Installing Role dependencies
      ansible.builtin.apt:
        name: ['kmod']
        state: present

- name: Prepare tester
  hosts: test-ag-nftables-tester
  tasks:
    - name: Installing testing utils
      ansible.builtin.apt:
        name: ['nmap']
        state: present
